<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="Comuna.aspx.cs" Inherits="Comuna" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" runat="Server">
    <asp:scriptmanager id="ScriptManager1" runat="server"></asp:scriptmanager>
    <div class="container">
        <div class="row">
            <asp:updatepanel id="UpdatePanel2" runat="server">
                        <ContentTemplate>
             <p>
                <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
                </asp:DropDownList>
            </p>

            <p>
                <asp:dropdownlist id="DropDownList2" runat="server">
                </asp:dropdownlist>
            </p>
                   </ContentTemplate>
                    </asp:updatepanel>
            <div class="input-field col s12 m12 l12" style="margin-top: 2%;">
                <asp:textbox runat="Server" id="txt_Comuna" name="comuna" type="text" class="validate" length="35"></asp:textbox>
                <label for="account_circle">Comuna</label>
            </div>
            <div class="row">
                <div class="input-submit">
                    <asp:updatepanel id="UpdatePanel1" runat="server">
                        <ContentTemplate>
                            <asp:Button runat="server" type="submit" ID="btn_insert" class="btn waves-effect waves-light deep-orange" name="action" Style="left: 3%;" OnClick="Button1_Click" Text="Registro" />
                            <br />
                            <asp:Label ID="lbl_mensaje" runat="server" Text="" CssClass="orange-text"></asp:Label>
                        </ContentTemplate>
                    </asp:updatepanel>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <asp:gridview id="GridView1" runat="server" autogeneratecolumns="False" autogeneratedeletebutton="True" autogenerateeditbutton="True" autogenerateselectbutton="True" datakeynames="comuna_id" datasourceid="SqlDataSource1" allowpaging="True" width="594px">
            <Columns>
                <asp:BoundField DataField="comuna_id" Visible="false" HeaderText="comuna_id" InsertVisible="False" ReadOnly="True" SortExpression="comuna_id" />
                <asp:BoundField DataField="comuna_nombre" HeaderText="comuna_nombre" SortExpression="comuna_nombre" />
                <asp:BoundField DataField="provincia_id" Visible="false" HeaderText="provincia_id" SortExpression="provincia_id" />
                <asp:TemplateField HeaderText="Provincia" SortExpression="Provincia">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList3" runat="server" DataSourceID="SqlDataSource2"
                            DataTextField="provincia_nombre" DataValueField="provincia_id"
                            SelectedValue='<%# Bind("provincia_id")%>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("provincia_nombre")%>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <PagerSettings FirstPageText="Primera Pagina" LastPageText="Ultima Pagina" Mode="NumericFirstLast" NextPageText="1" />
        </asp:gridview>
        <asp:sqldatasource id="SqlDataSource1" runat="server" connectionstring="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString %>" selectcommand="exec ListaComunas" deletecommand="DELETE FROM comunas WHERE comuna_id = @comuna_id" updatecommand="UPDATE comunas SET comuna_nombre = @comuna_nombre, provincia_id = @provincia_id WHERE (comuna_id = @comuna_id)"></asp:sqldatasource>
        <asp:sqldatasource id="SqlDataSource2" runat="server" connectionstring="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString %>" selectcommand="SELECT provincia_id, provincia_nombre FROM [provincias]"></asp:sqldatasource>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
</asp:Content>

