<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="EstadoUsuario.aspx.cs" Inherits="EstadoUsuario" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" Runat="Server">
      <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <div class="container">
        <div class="row">
            <div class="input-field col s12 m12 l12">
                <asp:TextBox runat="Server" ID="txt_estado" name="estado" type="text" class="validate" length="35"></asp:TextBox>
                <label for="account_circle">Estado </label>
            </div>
            <div class="row">
                <div class="input-submit">
                    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                        <ContentTemplate>
                            <asp:Button runat="server"  type="submit" ID="btn_insert" class="btn waves-effect waves-light deep-orange" name="action" style="left:3%;" OnClick="Button1_Click" Text="Registro" />
                            <br />
                            <asp:Label ID="lbl_mensaje" runat="server" Text="" CssClass="orange-text"></asp:Label>
                        </ContentTemplate>
                    </asp:UpdatePanel>
                </div>
            </div>
        </div>
    </div>
    <div class=" container center">
        <asp:gridview runat="server"  AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="id_Estado" DataSourceID="SqlDataSource1"  OnSelectedIndexChanged="Unnamed1_SelectedIndexChanged" CssClass="bordered responsive-table" ID="GridView1">
            <Columns>
                <asp:BoundField DataField="id_Estado"  Visible="false" HeaderText="id_Estado" ReadOnly="True" SortExpression="id_Estado" />
                <asp:BoundField DataField="Estado" HeaderText="Estado" SortExpression="Estado" />
            </Columns>
        </asp:gridview>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString8 %>" SelectCommand="SELECT * FROM [Estado]" DeleteCommand="DELETE FROM Estado WHERE (id_Estado = @id_Estado)" UpdateCommand="UPDATE Estado SET Estado = @Estado WHERE id_Estado = @id_Estado"></asp:SqlDataSource>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
</asp:Content>

