<%@ Page Title="" Language="C#" MasterPageFile="Admin.master" AutoEventWireup="true" CodeFile="Estado.aspx.cs" Inherits="Estado" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" Runat="Server">
       <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <div class="container">
        <div class="row">
            <div class="input-field col s12 m12 l12">
                <asp:TextBox runat="Server" ID="txt_estadoA" name="estadoA" type="text" class="validate" length="35"></asp:TextBox>
                <label for="account_circle">Estado Animal</label>
            </div>
            <div class="row">
                <div class="input-submit">
                    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                        <ContentTemplate>
                            <asp:Button runat="server"  type="submit" ID="btn_insert" class="btn waves-effect waves-light deep-orange" name="action" style="left:3%;" OnClick="Button1_Click" Text="Registro" />
                            <br/>
                            <asp:Label ID="lbl_mensaje" runat="server" Text="" CssClass="orange-text"></asp:Label>
                        </ContentTemplate>
                    </asp:UpdatePanel>
                </div>
            </div>
        </div>
    </div>
    <div class=" container">
        <asp:GridView CssClass="bordered responsive-table" ID="GridView1" runat="server" DataKeyNames="id_EstadoA" DataSourceID="SqlDataSource2" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGenerateColumns="False">
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="id_EstadoA" Visible="false" HeaderText="id_EstadoA" ReadOnly="True" SortExpression="id_EstadoA" />
                <asp:BoundField DataField="EstadoA"  HeaderText="EstadoA" SortExpression="EstadoA" >
                </asp:BoundField>
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString6 %>" SelectCommand="SELECT * FROM [Estado_Animal]" UpdateCommand="UPDATE Estado_Animal SET EstadoA = @EstadoA WHERE id_EstadoA = @id_EstadoA" DeleteCommand="DELETE FROM Estado_Animal WHERE id_EstadoA = @id_EstadoA"></asp:SqlDataSource>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
</asp:Content>

