<%@ Page Title="" Language="C#" MasterPageFile="Admin.master" AutoEventWireup="true" CodeFile="Genero.aspx.cs" Inherits="Genero" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" Runat="Server">
        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <div class="container">
        <div class="row">
            <div class="input-field col s12 m12 l12">
                <asp:TextBox runat="Server" ID="txt_genero" name="genero" type="text" class="validate" length="35"></asp:TextBox>
                <label for="account_circle">Genero</label>
            </div>
            <div class="row">
                <div class="input-submit">
                    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                        <ContentTemplate>
                            <asp:Button runat="server" type="submit" ID="btn_insert" class="btn waves-effect waves-light deep-orange" name="action" style="left:3%;" OnClick="Button1_Click" Text="Registro" />
                            <br />
                            <asp:Label ID="lbl_mensaje" runat="server" Text="" CssClass="orange-text"></asp:Label>
                        </ContentTemplate>
                    </asp:UpdatePanel>
                </div>
            </div>
        </div>
    </div>
    <div class=" container">
         <asp:GridView  CssClass="bordered responsive-table "  ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="idGenero" DataSourceID="SqlDataSource1" Height="292px" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
        <Columns>
            <asp:BoundField DataField="idGenero" Visible="false" HeaderText="idGenero" ReadOnly="True" SortExpression="idGenero" />
            <asp:BoundField DataField="Genero" HeaderText="Genero" SortExpression="Genero"  >
            </asp:BoundField>
        </Columns>
    </asp:GridView>
    </div>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString3 %>" SelectCommand="SELECT * FROM [Genero]" DeleteCommand="DELETE FROM Genero WHERE (idGenero = @idGenero)" UpdateCommand="UPDATE Genero SET Genero = @Genero WHERE idGenero = @idGenero"></asp:SqlDataSource>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
</asp:Content>

