<%@ Page Title="" Language="C#" MasterPageFile="Admin.master" AutoEventWireup="true" CodeFile="Mascota.aspx.cs" Inherits="Mascota" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" runat="Server">
    <asp:scriptmanager runat="server"></asp:scriptmanager>
    <div class="container center-block">
        <div style="border: 1px solid black; margin-bottom: 3%; margin-top: 2%;">
            <asp:fileupload runat="server" id="Img"></asp:fileupload>
            <asp:image runat="server" id="Image1"></asp:image>
            <asp:updatepanel runat="server">
              <ContentTemplate>
                  <asp:button runat="server" type="submit"  text="Subir" onclick="Unnamed3_Click" /> 
              </ContentTemplate> 
            </asp:updatepanel>
        </div>
    </div>
    <div class="container" style="margin-top:10%;">
        <div class="row">
            <div class="input-field col s12 m12 l3">
                <asp:textbox runat="Server" id="txt_Nombre" name="nombre" type="text" class="validate" length="8"></asp:textbox>
                <label for="account_circle">Nombre</label>
            </div>
            <div class="input-field col s12 m12 l3">
                <asp:textbox runat="Server" id="txt_raza" name="raza" type="text" class="validate" length="55"></asp:textbox>
                <label for="account_circle">Raza</label>
            </div>
            <div class="input-field col s12 m12 l3">
                <asp:textbox runat="Server" id="txt_estado" name="estado" type="text" class="validate" length="55"></asp:textbox>
                <label for="account_circle">Estado</label>
            </div>
            <div class="input-field col s12 m12 l3">
                <asp:textbox runat="Server" id="txt_Comuna" name="comuna" type="text" class="validate"></asp:textbox>
                <label for="account_circle">Comuna</label>
            </div>

            <div class="input-field col s12 m12 l4">
                <asp:textbox runat="Server" id="txt_tipo" name="tipo" type="text" class="validate"></asp:textbox>
                <label for="account_circle">Tipo</label>
            </div>
            <div class="input-field col s12 m12 l4">
                <asp:textbox runat="Server" id="txt_descripcion" name="descripcion" type="text" class="validate" length="12"></asp:textbox>
                <label for="icon_telephone">Descripcion</label>
            </div>
            <div class="input-field col s12 m12 l4">
                <asp:textbox runat="Server" id="txt_genero" name="Genero" type="text" class="validate"></asp:textbox>
                <label for="account_circle">Genero</label>
            </div>
            <div class="input-field col s12 m12 l4">
           <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                        <ContentTemplate>
                            <asp:Button runat="server" type="submit" ID="btn_insert" class="btn waves-effect waves-light deep-orange" name="action" Style="right: 10%" OnClick="Button1_Click" Text="Registro" />
                            <br />
                            <asp:Label ID="lbl_mensaje" runat="server" Text="" CssClass="orange-text"></asp:Label>
                        </ContentTemplate>
                    </asp:UpdatePanel>
            </div>
        </div>
    </div>
    <div class=" container" style="border: 1px solid black;">
        <asp:gridview cssclass="bordered responsive-table" id="GridView1" runat="server" autogeneratecolumns="False" datakeynames="id_Animal" datasourceid="SqlDataSource1" autogenerateselectbutton="True" onselectedindexchanged="GridView1_SelectedIndexChanged" autogeneratedeletebutton="True" autogenerateeditbutton="True" selectedindex="1">
            <Columns>
                <asp:BoundField DataField="id_Animal" Visible="false" HeaderText="id_Animal" SortExpression="id_Animal" ReadOnly="True" InsertVisible="False" />
                 <asp:BoundField DataField="Nombre" HeaderText="Nombre" SortExpression="Nombre" />
                 <asp:BoundField DataField="id_Raza" HeaderText="id_Raza" SortExpression="id_Raza" />
                <asp:BoundField DataField="id_EstadoA" HeaderText="id_EstadoA" SortExpression="id_EstadoA" />
                <asp:BoundField DataField="comuna_id" HeaderText="comuna_id" SortExpression="comuna_id" />
                <asp:BoundField DataField="id_TipoA" HeaderText="id_TipoA" SortExpression="id_TipoA" />
                <asp:BoundField DataField="Descripcion" HeaderText="Descripcion" SortExpression="Descripcion" />
                <asp:BoundField DataField="idGenero" HeaderText="idGenero" SortExpression="idGenero" />
                <asp:BoundField  Visible ="false" DataField="imagen" HeaderText="imagen" SortExpression="imagen" />
            </Columns>
    </asp:gridview>
    </div>
    <asp:sqldatasource id="SqlDataSource1" runat="server" connectionstring="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString %>" selectcommand="SELECT * FROM [Animal]"></asp:sqldatasource>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
</asp:Content>

