<%@ Page Title="" Language="C#" MasterPageFile="Admin.master" AutoEventWireup="true" CodeFile="Provincia.aspx.cs" Inherits="Provincia" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" runat="Server">
    <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <div class="container">
        <div class="row">
            <p>
                <asp:DropDownList ID="DropDownList1" runat="server" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
                </asp:DropDownList>
            </p>
            <div class="input-field col s12 m12 l12" style="margin-top: 10%;">
                <asp:TextBox runat="Server" ID="txt_Provincia" name="provincia" type="text" class="validate" length="35"></asp:TextBox>
                <label for="account_circle">Provincia</label>
            </div>
            <div class="row">
                <div class="input-submit">
                    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                        <ContentTemplate>
                            <asp:Button runat="server" type="submit" ID="btn_insert" class="btn waves-effect waves-light deep-orange" name="action" Style="left: 3%;" OnClick="Button1_Click" Text="Registro" />
                            <br />
                            <asp:Label ID="lbl_mensaje" runat="server" Text="" CssClass="orange-text"></asp:Label>
                        </ContentTemplate>
                    </asp:UpdatePanel>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <asp:GridView CssClass="bordered responsive-table" ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="provincia_id,region_id" DataSourceID="SqlDataSource1" PagerSettings-FirstPageText="Primera" PagerSettings-LastPageText="ultima" PagerSettings-NextPageText="1" AllowPaging="True">
            <Columns>
                <asp:BoundField DataField="provincia_nombre" HeaderText="provincia_nombre" SortExpression="provincia_nombre" />
                <asp:BoundField DataField="region_nombre" Visible="false" HeaderText="region_nombre" SortExpression="region_nombre" />
                <asp:BoundField DataField="provincia_id" Visible="false" HeaderText="provincia_id" InsertVisible="False" ReadOnly="True" SortExpression="provincia_id" />
                <asp:BoundField DataField="region_id" Visible="false" HeaderText="region_id" InsertVisible="False" ReadOnly="True" SortExpression="region_id" />
                <asp:TemplateField HeaderText="Region" SortExpression="Region">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList3" runat="server" DataSourceID="SqlDataSource2"
                            DataTextField="region_nombre" DataValueField="region_id"
                            SelectedValue='<%# Bind("region_id")%>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("region_nombre")%>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>

            <PagerSettings FirstPageText="Primera" LastPageText="ultima" NextPageText="1" Mode="NumericFirstLast"></PagerSettings>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString %>" SelectCommand="ListaProvincia" SelectCommandType="StoredProcedure" DeleteCommand="DELETE FROM provincias WHERE (provincia_id = @provincia_id)" UpdateCommand="UPDATE provincias SET provincia_nombre = @provincia_nombre, region_id = @region_id WHERE provincia_id = @provincia_id"></asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString %>" SelectCommand="SELECT * FROM [regiones]"></asp:SqlDataSource>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
</asp:Content>

