<%@ Page Title="" Language="C#" MasterPageFile="Admin.master" AutoEventWireup="true" CodeFile="Tipo.aspx.cs" Inherits="Tipo" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" Runat="Server">
       <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <div class="container">
        <div class="row">
            <div class="input-field col s12 m12 l12">
                <asp:TextBox runat="Server" ID="txt_tipo" name="tipo" type="text" class="validate" length="35"></asp:TextBox>
                <label for="account_circle">Tipo Animal</label>
            </div>
            <div class="row">
                <div class="input-submit">
                    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                        <ContentTemplate>
                            <asp:Button runat="server"  type="submit" ID="btn_insert" class="btn waves-effect waves-light deep-orange" name="action" style="left:3%;" OnClick="Button1_Click" Text="Registro" />
                            <br />
                            <asp:Label ID="lbl_mensaje" runat="server" Text="" CssClass="orange-text"></asp:Label>
                        </ContentTemplate>
                    </asp:UpdatePanel>
                </div>
            </div>
        </div>
    </div>
    <div class=" container">
        <asp:GridView CssClass="bordered responsive-table" ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="id_TipoA" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleted="GridView1_RowDeleted" OnRowDeleting="GridView1_RowDeleting" AllowSorting="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGenerateSelectButton="True">
            <Columns>
                <asp:BoundField DataField="id_TipoA" Visible="false" HeaderText="id_TipoA" ReadOnly="True" SortExpression="id_TipoA" />
                <asp:BoundField DataField="tipo_Animal" HeaderText="tipo Animal" SortExpression="tipo_Animal" >
                </asp:BoundField>
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString5 %>" SelectCommand="SELECT * FROM [Tipo_Animal]" DeleteCommand="DELETE FROM Tipo_Animal WHERE (id_TipoA = @id_TipoA)" UpdateCommand="UPDATE Tipo_Animal SET tipo_Animal = @tipo_Animal where id_TipoA = @id_TipoA"></asp:SqlDataSource>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
</asp:Content>

