<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="Usuario.aspx.cs" Inherits="Usuario" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" runat="Server">
    <asp:scriptmanager runat="server"></asp:scriptmanager>
    <div class="container">
        <div class="row">
            <div class="input-field col s12 m12 l6">
                <asp:textbox runat="Server" id="txt_usuario" name="usuario" type="text" class="validate"></asp:textbox>
                <label for="account_circle">Usuario</label>
            </div>
            <div class="input-field col s12 m12 l6">
                <asp:textbox runat="Server" id="txt_pass" dar name="password" type="password" class="validate"></asp:textbox>
                <label for="account_circle">pass</label>
            </div>
            <p>
                <label for="account_circle">Tipo</label>
                <asp:dropdownlist id="DropDownList3" runat="server"></asp:dropdownlist>
            </p>
            <p>
                <label for="account_circle">Estado</label>
                <asp:dropdownlist id="DropDownList4" runat="server"></asp:dropdownlist>
            </p>
            <div class="row">
                <div class="input-submit">
                    <asp:updatepanel id="UpdatePanel1" runat="server">
                        <ContentTemplate>
                            <asp:Button runat="server" type="submit" ID="btn_insert" class="btn waves-effect waves-light deep-orange" name="action" Style="margin-left:35%;" OnClick="btn_insert_Click1" Text="Registro"/> <br/>
                            <asp:Label  ID="lbl_mensaje" runat="server" Text="" cssClass="orange-text"></asp:Label>
                        </ContentTemplate>
                    </asp:updatepanel>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <asp:gridview runat="server" AutoGenerateColumns="False" DataKeyNames="idUsuario,id_Tipo,id_Estado" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" ID="Admin">
            <Columns>
                <asp:BoundField DataField="idUsuario" Visible = "false" HeaderText="idUsuario" InsertVisible="False" ReadOnly="True" SortExpression="idUsuario" />
                <asp:BoundField DataField="Usuario"   HeaderText="Usuario" SortExpression="Usuario" />
                <asp:BoundField DataField="Password" HeaderText="Password" DataFormatString="******" SortExpression="Password" />
                <asp:BoundField DataField="Tipo" Visible="false" HeaderText="Tipo" SortExpression="Tipo" />
                <asp:BoundField DataField="Estado" Visible="false"  HeaderText="Estado" SortExpression="Estado" />
                <asp:BoundField DataField="id_Tipo" Visible="false" HeaderText="id_Tipo" ReadOnly="True" SortExpression="id_Tipo" />
                <asp:BoundField DataField="id_Estado" Visible="false" HeaderText="id_Estado" InsertVisible="False" ReadOnly="True" SortExpression="id_Estado" />
                <asp:TemplateField HeaderText="Estado" SortExpression="Estado">
                        <EditItemTemplate>
                            <asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="SqlDataSource2"
                             DataTextField="Estado" DataValueField="id_Estado"
                                 SelectedValue='<%# Bind("id_Estado")%>'> 
                            </asp:DropDownList>                     
                        </EditItemTemplate>
                    <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("Estado")%>'></asp:Label>
                    </ItemTemplate> 
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Tipo" SortExpression="Tipo">
                        <EditItemTemplate>                    
                            <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource3"
                             DataTextField="Tipo" DataValueField="id_Tipo"
                                 SelectedValue='<%# Bind("id_Tipo") %>'> 
                            </asp:DropDownList>
                        </EditItemTemplate>
                    <ItemTemplate>
                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("Tipo")%>'></asp:Label>
                    </ItemTemplate> 
                </asp:TemplateField>
                 </Columns>
        </asp:gridview>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString %>" SelectCommand="viUsuario" SelectCommandType="StoredProcedure" DeleteCommand="DELETE FROM Usuario WHERE idUsuario = @idUsuario" UpdateCommand="UPDATE Usuario SET Usuario = @usuario, Password = @Password, id_Tipo = @id_Tipo, id_Estado = @id_Estado WHERE idUsuario = @idUsuario"></asp:SqlDataSource>
        <asp:sqldatasource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString %>" SelectCommand="SELECT * FROM [Estado]"></asp:sqldatasource>
        <asp:sqldatasource  ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString %>" SelectCommand="SELECT * FROM [Tipo]"></asp:sqldatasource>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
</asp:Content>

