<%@ Page Title="" Language="C#" MasterPageFile="Admin.master" AutoEventWireup="true" CodeFile="Vacunas.aspx.cs" Inherits="Vacunas" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" runat="Server">
    <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <div class="container">
        <div class="row">
            <div class="input-field col s12 m12 l12">
                <asp:TextBox runat="Server" ID="txt_vacuna" name="vacuna" type="text" class="validate" length="35"></asp:TextBox>
                <label for="account_circle">Vacunas</label>
            </div>
            <div class="row">
                <div class="input-submit">
                    <asp:updatepanel id="UpdatePanel1" runat="server">
                        <ContentTemplate>
                            <asp:Button runat="server" type="submit" ID="btn_insert" class="btn waves-effect waves-light deep-orange" name="action" Style="right: 10%" OnClick="btn_insert_Click1" Text="Registro"/> <br/>
                            <asp:Label  ID="lbl_mensaje" runat="server" Text="" cssClass="orange-text"></asp:Label>
                        </ContentTemplate>
                    </asp:updatepanel>
                </div>
            </div>
        </div>
    </div>
    <div class=" container">
        <asp:GridView ID="GridView1"  CssClass="bordered responsive-table" runat="server" AutoGenerateColumns="False" DataKeyNames="id_TipoVacuna" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
            <Columns>
                <asp:BoundField DataField="id_TipoVacuna" Visible="false" HeaderText="id_TipoVacuna" ReadOnly="True" SortExpression="id_TipoVacuna" />
                <asp:BoundField DataField="tipoVacuna" HeaderText="tipoVacuna" SortExpression="tipoVacuna" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString7 %>" SelectCommand="SELECT * FROM [Tipo_Vacuna]" DeleteCommand="DELETE FROM Tipo_Vacuna WHERE id_TipoVacuna = @id_TipoVacuna" UpdateCommand="UPDATE Tipo_Vacuna SET tipoVacuna = @tipoVacuna WHERE id_TipoVacuna = @id_TipoVacuna"></asp:SqlDataSource>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
</asp:Content>

