<%@ Page Title="" Language="C#" MasterPageFile="Admin.master" AutoEventWireup="true" CodeFile="Veterinario.aspx.cs" Inherits="Veterinario" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Contenido" runat="Server">
    <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <div class="container">
        <div class="row">
            <p>
                <label for="account_circle">Masacotaa</label>
                <asp:DropDownList ID="DropDownList3" runat="server"></asp:DropDownList>
            </p>
            <p>
                <label for="account_circle">Usuario</label>
                <asp:DropDownList ID="DropDownList4" runat="server"></asp:DropDownList>
            </p>
            <div class="input-field col s12 m12 l12">
                <asp:TextBox runat="Server" ID="txt_descripcion" name="Descripcion" type="text" class="validate" length="35"></asp:TextBox>
                <label for="account_circle">Descripcion</label>
            </div>
            <div>
                 <label for="account_circle">Fecha</label>
                <input type="date" runat="server" id="fecha" class="datepicker">
            </div>
            <div class="row">
                <div class="input-submit">
                    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                        <ContentTemplate>
                            <asp:Button runat="server" type="submit" ID="btn_insert" class="btn waves-effect waves-light deep-orange" name="action" Style="left: 3%;" OnClick="Button1_Click" Text="Registro" />
                            <br />
                            <asp:Label ID="lbl_mensaje" runat="server" Text="" CssClass="orange-text"></asp:Label>
                        </ContentTemplate>
                    </asp:UpdatePanel>
                </div>
            </div>
        </div>
    </div>
    <div class="container center" >
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_Visita,id_Animal,idUsuario" DataSourceID="SqlDataSource1"  Width="20%">
            <Columns>
                <asp:BoundField  DataField ="id_Visita" Visible="false" HeaderText="id_Visita" InsertVisible="False" ReadOnly="True" SortExpression="id_Visita" />
                <asp:BoundField DataField="Fecha" HeaderText="Fecha" SortExpression="Fecha" />
                <asp:BoundField DataField="Descripcion" HeaderText="Descripcion" SortExpression="Descripcion" />
                <asp:BoundField DataField="Nombre" Visible="false" HeaderText="Nombre" SortExpression="Nombre" />
                <asp:BoundField DataField="Usuario" Visible="false" HeaderText="Usuario" SortExpression="Usuario" />
                <asp:BoundField DataField="id_Animal" Visible="false" HeaderText="id_Animal" InsertVisible="False" ReadOnly="True" SortExpression="id_Animal" />
                <asp:BoundField DataField="idUsuario" Visible="false" HeaderText="idUsuario" InsertVisible="False" ReadOnly="True" SortExpression="idUsuario" />
                 <asp:TemplateField HeaderText="Mascota" SortExpression="Mascota">    
                <EditItemTemplate>
                            <asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="SqlDataSource2"
                             DataTextField="Nombre" DataValueField="id_Animal"
                                 SelectedValue='<%# Bind("id_Animal")%>'> 
                            </asp:DropDownList>                     
                        </EditItemTemplate>
                    <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("Nombre")%>'></asp:Label>
                    </ItemTemplate> 
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Usuario" SortExpression="Usuario">
                        <EditItemTemplate>                    
                            <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource3"
                             DataTextField="Usuario" DataValueField="idUsuario"
                                 SelectedValue='<%# Bind("idUsuario") %>'> 
                            </asp:DropDownList>
                        </EditItemTemplate>
                    <ItemTemplate>
                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("Usuario")%>'></asp:Label>
                    </ItemTemplate> 
                </asp:TemplateField>
                     </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString %>" SelectCommand="VisitaVet" SelectCommandType="StoredProcedure" DeleteCommand="DELETE FROM VisitaVeterinario WHERE id_Visita = @id_Visita" UpdateCommand="UPDATE VisitaVeterinario SET Fecha = @Fecha, id_Animal = @id_Animal, idUSuario = @idUsuario, Descripcion = @Descripcion WHERE id_Visita = @id_Visita"></asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString %>" SelectCommand="SELECT [id_Animal], [Nombre] FROM [Animal]"></asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:bd_AdopcionAnimalConnectionString %>" SelectCommand="SELECT [idUsuario], [Usuario] FROM [Usuario]"></asp:SqlDataSource>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
</asp:Content>

